server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: link-shortener

link-shortener:
  short-link-length: 8
  logging:
    enable-log-execution-time: false
