server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: link-shortener
  datasource:
    url: jdbc:postgresql://localhost:5433/mentoring
    username: dev
    password: Ab123456
    hikari:
      schema: link_shortener
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  liquibase:
    change-log: ./db/changelog/changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate

link-shortener:
  short-link-length: 8
  #every day at 11pm
  remove-old-link-infos:
    cron: "0 0 23 * * *"

logging:
  enabled-log-execution-time: false
  web-logging:
    enabled: true
    log-body: true
